// Сборка плоского GAS-бандла: dist/gm-stats.gas.js.
//
// Формат — как engine.gas.js у слотов: файл БЕЗ import/export, который игра конкатенирует в свой
// GAS-бандл своим tools/build.js (и в node-бандл тем же куском — код один, рантайма два).
//
// Внутренности спрятаны в IIFE (esbuild, globalName GmStats), наружу торчат только публичные
// имена — их же алиасы `var X = GmStats.X;` в подвале делают глобальными функциями Apps Script.
// Так у внутренних хелперов ядра нет ни одного шанса столкнуться с именами игры (это надёжнее
// префикса `gs`, который пришлось бы держать руками).

import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';

const result = await build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  write: false,
  format: 'iife',
  globalName: 'GmStats',
  platform: 'neutral',
  target: 'es2020',
  legalComments: 'none'
});

const iife = result.outputFiles[0].text;

// Публичные имена берём из самого бандла: список не дублируется руками и не протухает.
const ctx = {};
vm.createContext(ctx);
vm.runInContext(iife, ctx);
const names = Object.keys(ctx.GmStats).sort();
if (!names.length) throw new Error('build-gas: бандл не отдал ни одного экспорта');

const aliases = names.map((n) => `var ${n} = GmStats.${n};`).join('\n');
const out =
  '// @gmbl/gm-stats — GAS bundle. AUTO-GENERATED by build-gas.mjs. Do not edit.\n' +
  '// Плоский файл для Apps Script: ни import, ни export. Внутренности — в замыкании GmStats,\n' +
  `// наружу ${names.length} глобальных имён (см. подвал файла).\n\n` +
  iife +
  '\n// --- Публичные имена ядра как глобальные функции Apps Script ---\n' +
  aliases + '\n';

mkdirSync('dist', { recursive: true });
writeFileSync('dist/gm-stats.gas.js', out, 'utf8');
console.log(`GAS bundle: dist/gm-stats.gas.js (${names.length} имён, ${out.length} байт)`);
